VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "cDLL_DummyInit"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'*************************************************************************************************************************************************************************************************************************************************
'
' This module is from the vbAdvance product © 2001 - 2007 Young Dynamic Software. All rights reserved.
'
' vbAdvance is now unsupported freeware - see http://vb.mvps.org/tools/vbAdvance/
'
'*************************************************************************************************************************************************************************************************************************************************

Option Explicit

Sub initVBCall()
End Sub
